Repository Man0Lulu/Pi---mobile, pull requests merged in 2023-11, with the labels that each got.

#55 Implementado Tela de Inicio sem Hábitos, Adicionar imagem na Tela de Perfil e Criar Hábito. Autenticação atualizada para receber dados da pessoa. #39, #48, #50
  App.js
  app.json
  assets/botaoadd.svg
  assets/fonts/Inter-Black.ttf
  assets/habito-default.png
  assets/menu.jpg
  assets/svgtopng.zip
  components/BotaoStyles.js
  components/DiasHabitos.js
  components/Switch.js
  contexts/HabitoContext.js
  contexts/UserContext.js
  package-lock.json
  package.json
  routes/AppRoute.js
  screens/CriarHabito.js
  screens/Home.js
  screens/Perfil.js
  services/AuthService.js
  services/HabitoService.js
  styles/CriarHabitoStyles.js
  styles/HomeStyles.js
  svg/BotaoAdd.js
  svg/IconeUsuario.js
  svg/MenuSVG.js
Labels: Autenticação do usuário, Hábitos (CRUD), Edição de Perfil de Usuário

#57 Criando Modal e funcionalidade de deletar conta na Tela de Perfil
  components/Aviso.js
  contexts/UserContext.js
  package-lock.json
  package.json
  screens/Perfil.js
  services/AuthService.js
  services/UsuarioService.js
  styles/PerfilStyles.js
Labels: Autenticação do usuário, Hábitos (CRUD), Edição de Perfil de Usuário

#60 Pagina de editar hábito criada #59
  components/SearchBar.js
  contexts/HabitoContext.js
  routes/AppRoute.js
  routes/AutenticacaoRoute.js
  screens/AlterarHabito.js
Labels: Hábitos (CRUD)

#62 Validações Adicionadas #61
  screens/AlterarHabito.js
  screens/Cadastro.js
  screens/CriarHabito.js
  screens/Login.js
  screens/Perfil.js
Labels: Hábitos (CRUD)

#69 Correção Estilos Gerais #68
  components/BotaoStyles.js
  screens/Cadastro.js
  screens/Login.js
  screens/Perfil.js
  styles/BoasVindasStyles.js
  styles/CadastroStyles.js
  styles/CriarHabitoStyles.js
  styles/LoginStyles.js
  styles/PerfilStyles.js
Labels: enhancement

#71 ScrollView adicionada na tela de boas vindas. #70
  screens/AlterarHabito.js
  screens/BoasVindas.js
  styles/BoasVindasStyles.js
  styles/StylesGlobal.js
Labels: enhancement
